# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloud_storage_pb2 as cloud__storage__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cloud_storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/cloudstorage.CloudStorageService/UploadFile',
                request_serializer=cloud__storage__pb2.UploadRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_unary(
                '/cloudstorage.CloudStorageService/DownloadFile',
                request_serializer=cloud__storage__pb2.DownloadRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/cloudstorage.CloudStorageService/DeleteFile',
                request_serializer=cloud__storage__pb2.DeleteRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/cloudstorage.CloudStorageService/ListFiles',
                request_serializer=cloud__storage__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.ListFilesResponse.FromString,
                _registered_method=True)


class CloudStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=cloud__storage__pb2.UploadRequest.FromString,
                    response_serializer=cloud__storage__pb2.UploadResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=cloud__storage__pb2.DownloadRequest.FromString,
                    response_serializer=cloud__storage__pb2.DownloadResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=cloud__storage__pb2.DeleteRequest.FromString,
                    response_serializer=cloud__storage__pb2.DeleteResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=cloud__storage__pb2.ListFilesRequest.FromString,
                    response_serializer=cloud__storage__pb2.ListFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudstorage.CloudStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloudstorage.CloudStorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudstorage.CloudStorageService/UploadFile',
            cloud__storage__pb2.UploadRequest.SerializeToString,
            cloud__storage__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudstorage.CloudStorageService/DownloadFile',
            cloud__storage__pb2.DownloadRequest.SerializeToString,
            cloud__storage__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudstorage.CloudStorageService/DeleteFile',
            cloud__storage__pb2.DeleteRequest.SerializeToString,
            cloud__storage__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudstorage.CloudStorageService/ListFiles',
            cloud__storage__pb2.ListFilesRequest.SerializeToString,
            cloud__storage__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
